### ISSUE TITLE
Add text to speech for translations

### ISSUE THREAD

**Issue by r2dev2** [KentoNishi/LiveTL#111]
**Is your feature request related to a problem? Please describe.**
When watching streams, it is sometimes hard to concentrate on translations and the content.

**Describe the solution you'd like**
I propose an optional text to speech mode in which translations are spoken by the computer. An example partial implementation in javascript is
```js
function speak(text) {
  const utterance = new SpeechSynthesisUtterance(text);
  speechSynthesis.speak(utterance);
}
speak("translation");
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Candygoblen123** [comment]
Does this work in chrome and Firefox

**Comment by r2dev2** [comment]
It works in all browsers but Internet Explorer. Here is the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis#Browser_compatibility).

**Comment by Candygoblen123** [comment]
Sweet. We should make this toggle-able and  maybe disabled by default.

**Comment by r2dev2** [comment]
Has been added by commit #cb355d4.
