### ISSUE TITLE
Brave - Holotools doesn't render correctly

### ISSUE THREAD

**Issue by Candygoblen123** [KentoNishi/LiveTL#136]
**Describe the bug**
When using brave browser, on holotools, when you click the expand translations button, YTC and LiveTL does not render correctly.

**To Reproduce**
1. Open a stream on holotools in Brave Browser
2. Click on expand translations

**Expected behavior**
The translations pane appears like in other browsers

**Screenshots**
Screenshot of incorrect rendering
![unknown](https://user-images.githubusercontent.com/28193374/104096213-18707900-5269-11eb-8720-749dd966fc88.png)

**Desktop (please complete the following information):**
 - Browser: Brave
 - Version: v4.0.21

**Additional context**

**Comment by r2dev2** [comment]
The problem is ``parseParams`` failing while detecting horniness.

**Comment by r2dev2** [comment]
Solved in 4c5132bb867269f9bfad767728cff12944c294d1.
