### ISSUE TITLE
Favicon messed up

### ISSUE THREAD

**Issue by r2dev2** [KentoNishi/LiveTL#139]
**Describe the bug**
The favicon for LiveTL gets messed up by horny mode.

**To Reproduce**
1 - Use LiveTL to watch a Marine stream
2 - Notice that when you open other streams in LiveTL, sometimes the ``BL`` favicon will be used and sometimes, the favicon will go away.

**Expected behavior**
The BL favicon should only appear when watching Houshou Marine.

**Screenshots**
![image](https://user-images.githubusercontent.com/50760816/104142839-147c4e00-5372-11eb-8b00-de74de80eb78.png)

**Additional context**
Reported by SPCresent in the Discord

**Comment by Shadowlauch** [comment]
Not sure if this is expected behavior, but I was watching Okayu's stream in LiveTL today and opened Marine's normally in youtube and even though I'm not using LiveTL for Marine's stream, it is still displaying the icon.

**Comment by r2dev2** [comment]
Yea, that's a bug. The status of the bug fix right now is getting it to reliably appear in a clean selenium install so it can be added to our tests.
