### ISSUE TITLE
[Bug] Sharing LiveTL with your friends link does nothing

### ISSUE THREAD

**Issue by arbrog** [KentoNishi/LiveTL#17]
Browser: Chrome  87.0.4280.66
OS: Windows 10
Adblock: disabled

The "sharing LiveTL with your friends" link currently doesn't do anything. Looking at the [href](https://github.com/KentoNishi/LiveTL/blob/00d12eb4f262fa8632ec829949ba955d2ce3ba78/LiveTL/js/frame.js#L405) it's currently pointing to `javascript:void(0);`. I imagine this isn't so much a bug as just something you haven't gotten to yet.

**Comment by KentoNishi** [comment]
Hm, it's supposed to open the device native share menu. I'll look into it when I have time, thanks for the report!

**Comment by Candygoblen123** [comment]
The Navigator.share() method used is only available in Microsoft Edge 81+ and Safari 12.1+.  We would implement a share screen for browsers that do not support Navigator.share() and use the Navigator.canShare() method to determine which implementation should be used.

**Comment by KentoNishi** [comment]
I figured it out. I forgot to put `await` before getFile lmao
