### ISSUE TITLE
Extension doesn't catch translators using '[英訳/EN]' (and others) as prefix

### ISSUE THREAD

**Issue by FlaminSarge** [KentoNishi/LiveTL#25]
Sometimes, translators use the above string for the prefix on their translation messages, which currently doesn't get caught by filter.js under its current rules.

I'd assume that this issue exists for other languages as well; it would be more flexible to be able to instead specify a custom prefix to watch for (in the event that for one particular instance of a stream, somebody decides to use a prefix that doesn't fall under a good set of rules). Ideally, custom prefix(es) would work on top of the existing preset prefixes instead of replacing or overriding the currently selected prefix.

**Comment by r2dev2bb8** [comment]
The reason why it's not detecting is that the backslash used is a Japanese backslash. If anyone has a list of Japanese backslash and bracket characters that mess up the detection, could you put them in replies?

**Comment by r2dev2bb8** [comment]
Prefix in title solved in dfa697c. Custom prefixes are in an upcoming feature list but I will caution that it will make our filter less efficient.
