### ISSUE TITLE
Developer captions

### ISSUE THREAD

**Issue by r2dev2bb8** [KentoNishi/LiveTL#52]
**Is your feature request related to a problem? Please describe.**
When developing the extension, if there are not translators in chat, one has to write test translation in chat which negatively affects the experiences of other LiveTL users.

**Describe the solution you'd like**
Add a developer caption. ex: [dev]

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by KentoNishi** [comment]
Use a vod omegalul

**Comment by r2dev2bb8** [comment]
Using archived vods may not accurately reflect conditions during stream.

**Comment by KentoNishi** [comment]
ChilledCow
