### ISSUE TITLE
translator not visualized

### ISSUE THREAD

**Issue by DarkFlame996** [KentoNishi/LiveTL#54]
**Describe the bug**
On a Fubuki stream one of the most "famous" translators doesnt get visualized on the embed

**Screenshots**
![Immagine 2020-12-09 000511](https://user-images.githubusercontent.com/40276313/101551951-4173c480-39b2-11eb-9194-0de593a9b12a.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version latest

**Comment by r2dev2bb8** [comment]
Could you please copy paste the text of the translation into this thread as local testing indicates that the translation should be detected. It may be due to Japanese characters that we haven't handled correctly.

**Comment by KentoNishi** [comment]
Newest version should fix this because we changed the detection method.
Also, text is `[英訳/EN]`
