### ISSUE TITLE
Cannot resize chat windows horizontally

### ISSUE THREAD

**Issue by gakiloroth** [KentoNishi/LiveTL#97]
**Describe the bug**
Cannot resize chat windows horizontally - vertically (resizing the live vs translated chat) works. LiveTL loads in like this:

![](https://i.imgur.com/X2oP3Tk.jpg)

Any attempt to resize the chat window left and right results in this(while holding down mouse button):

![](https://i.imgur.com/HITSwdQ.png)

and then this screen when mouse button is let go:

![](https://i.imgur.com/QGgxvIX.png)

**To Reproduce**
1. Go to a stream in LiveTL
2. Try to resize chat window horizontally

I am not fully sure what causes this - some stream chats work fine but most streams I cannot resize correctly.

**Expected behavior**

**Screenshots**
Before moving chat left and right:
![](https://i.imgur.com/X2oP3Tk.jpg)

While moving left and right AND mouse is held down:
![](https://i.imgur.com/HITSwdQ.png)

After letting go of mouse after attempting to resize left and right:
![](https://i.imgur.com/QGgxvIX.png)

If I try to resize again, it stays as this ^ above screenshot

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 87.0.4280.88

**Comment by r2dev2bb8** [comment]
I do not know how the code started doing that as it is passing the test for that behavior. I will fix this asap. Also, is this a build released to the official extension store or not?

**Comment by gakiloroth** [comment]
This is using the extension from the Chrome store yes. Again, I'm not sure what happened because it was working fine, but it started happening on some streams (usually id guess 40-60% of streams I cannot resize the chat on). I thought maybe the pinned message was causing it, but on the stream in my screenshot there wasn't a pinned message so I'm not sure. 

I can also send a video of the behavior incase that might be easier to diagnose (or a gif)

**Comment by r2dev2bb8** [comment]
That behavior was introduced when I changed the layout to use percentages instead of pixels. At one point, there was an error that resulted in a width of `NaN`. This causes the extension to mess up even after the fix. I don't know why this is on the Chrome official build though. The temporary solution that worked in the developer build is to reinstall the extension.

**Comment by gakiloroth** [comment]
reinstalling did seem to work this time (I did reinstall before but it didn't seem to fix the issue)

thanks for the solution! hope this issue helps fix it (or maybe it was a one off weirdness)

**Comment by r2dev2bb8** [comment]
This should have been fixed. If it still persists, open a new issue or ping us on discord.
