### ISSUE TITLE
[英訳/EN] is not captured

### ISSUE THREAD

**Issue by Tudi20** [KentoNishi/LiveTL#99]
**Describe the bug**
[英訳/EN] is not captured.

**To Reproduce**
1. Go to a livestream
2. Post something with `[英訳/EN]`.
3. Realise it's not captured.

**Expected behavior**
Message being captured.

**Desktop (please complete the following information):**
 - Firefox 84

**Comment by naters305** [comment]
Could you test and see if just the EN tag gets picked up. If it doesn't then it is a known issue with Firefox at the moment.

**Comment by Tudi20** [comment]
Yup, it doesn't.
